http:
  port: 3001
jwtConstants:
  secretToken: q3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaSgUkXp2s5v8y/B?E(H+MbQeTh
  refreshToken: refreshTOken_kjfbakhfba8ihjknfoahfohwnbetiyhweoarhbnflanl====abigsabf*bfdkjja7anjdf2
dataSource:
  redis:
    host: 192.168.50.166
    port: 6379
    password: "ticket@123"
  primary:
    host: 192.168.50.166
    username: "postgres"
    password: "infodevticket@123"
    port: 5432
    database: "db_ticketing"
  hris:
    IDENTITY_SERVER: http://172.23.1.130:1902
    AUTHORIZATION_ENDPOINT: http://172.23.1.130:1900/connect/authorize
    ISSUER: http://172.23.1.130:1900
    jwksuri: http://172.23.1.130:1900/.well-known/openid-configuration/jwks
    hr_url: http://172.23.1.130:1902
